module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  block_place: 0
  bootstrap_layouts: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  ds: 0
  ds_devel: 0
  ds_extras: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  kint: 0
  layout_discovery: 0
  libraries: 0
  lightgallery: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_facebook: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  poll: 0
  quickedit: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_templates: 0
  views_ui: 0
  webform: 0
  webform_bootstrap: 0
  webform_node: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  bartik: 0
  style: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
