favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost:8080/themes/custom/first/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  first: 8000
features:
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
  node_user_picture: false
logo:
  path: 'public://Webp.net-resizeimage_0.png'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
